language: node_js
sudo: required
node_js:
- '0.12'
services:
- mongodb
before_install: npm install -g mocha
install: npm install
deploy:
  provider: heroku 
  api_key: $HEROKU_KEY
  app: letrasgame
  revision_type: github
  on:
    repo: Quantium/letras
