language: node_js
node_js:
- '0.12'
services:
- mongodb
before_install: npm install -g mocha
install: npm install
deploy:
  provider: heroku 
  api_key: $HEROKU_APP_ID
  app: letrasgame
  revision_type: github
  deployment_group: Quantium
  on:
    repo: Quantium/letras
