language: node_js
node_js:
- '0.12'
services:
- mongodb
deploy:
  provider: heroku 
  api_key: $HEROKU_APP_ID
  app: isotoponet
  revision_type: github
  deployment_group: Quantium
  on:
    repo: Quantium/letras
